name: Create Release Build
on:
  workflow_dispatch:
    inputs:
      publicRelease:
        description: "If it is enabled then public build will be genreate"
        type: boolean
        required: false
        default: false

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v1
      - name: get build version 
        id: package-version
        run: |
          PACKAGE_VERSION=$(cat ./package.json | jq '.version' | tr -d '"')
          echo ::set-output name=current-version::$PACKAGE_VERSION
      - name: print version
         run: |
          echo ${{ steps.package-version.outputs.current-version}}
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Configure Git
        working-directory: .github/scripts
        env:
          GITHUBPAT: ${{ secrets.GITHUBPAT }}
        run: |
          ./configure_git.sh
          git checkout ${GITHUB_REF##*/}  
      - name: remove file
        run: |
            rm -rf package-lock.json && sed 's/build\///g' .gitignore > .gitignore
      - name: install and build
        run: |
          npm install && npm run build
      - name: commit and tag
        run: |
          git add .
          git commit -m "${{ steps.package-version.outputs.current-version}} published" 
          git tag ${{ steps.package-version.outputs.current-version}}
          git push --tags

         